service: access-count-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  environment:
    DYNAMODB_USERS_TABLE_NAME: ${self:custom.usersTableName}

custom: 
  usersTableName: users-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: '*'